# Generated by Django 6.0.1 on 2026-02-01 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=15)),
                ('reserved', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_question', models.TextField(blank=True, default='')),
                ('prompt_answer', models.TextField(blank=True, default='')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='exhibitionpages.timeslot')),
            ],
        ),
    ]
