# Generated by Django 6.0.1 on 2026-02-05 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='reserved',
        ),
        migrations.AlterField(
            model_name='registration',
            name='prompt_answer',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
